apiVersion: v1
clusters:
  - cluster:
      insecure-skip-tls-verify: true
      server: >-
        https://vcp-5c833b3d-16be-4dbd-8780-ab3a170ad04b.cloud-1717912500.spot.rackspace.com/
    name: saver9
contexts:
  - context:
      cluster: saver9
      namespace: default
      user: ngpc-user
    name: aws-saver9
  - context:
      cluster: saver9
      namespace: default
      user: oidc
    name: aws-saver9-oidc
current-context: aws-saver9
kind: Config
preferences: {}
users:
  - name: ngpc-user
    user:
      token: >-
        eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IkNYQ25nd1NFS0JWQl9DbWxvalo0eCJ9.eyJncm91cCI6ImNsb3Vkc3BhY2UtYWRtaW4iLCJnaXZlbl9uYW1lIjoiRXRoYW4iLCJmYW1pbHlfbmFtZSI6IkNvb3BlciIsIm5pY2tuYW1lIjoiaG9vbjMzNzEwIiwibmFtZSI6IkV0aGFuIENvb3BlciIsInBpY3R1cmUiOiJodHRwczovL2xoMy5nb29nbGV1c2VyY29udGVudC5jb20vYS9BQ2c4b2NKNmVuZUJQYl9ud0ZrSno3V2dyaElfXzEyNkVsZklzWHdkaDNudkxuMmZybU1Ub1E9czk2LWMiLCJ1cGRhdGVkX2F0IjoiMjAyNC0wNy0zMVQwMzoxMDowMS44OThaIiwiZW1haWwiOiJob29uMzM3MTBAZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsImlzcyI6Imh0dHBzOi8vbG9naW4uc3BvdC5yYWNrc3BhY2UuY29tLyIsImF1ZCI6Im13RzNsVU1WOEt5ZU1xSGU0Zko1QmIzbk0xdkJ2Uk5hIiwiaWF0IjoxNzIyMzk1NDA4LCJleHAiOjE3MjI2NTQ2MDgsInN1YiI6Imdvb2dsZS1vYXV0aDJ8MTA3NTEzODg4NjU4OTA2MzkxNDYwIiwic2lkIjoid2xlOVhrS2h1UGVWemdGYTVQTmE0MXVCa0NacXFmMHUiLCJub25jZSI6Ik9XWjZWa0k0WTA5ZkxYRXRjVXR6U1c1clJXdFZlRFJJVFhkeFJsQjBObWhSY0VaTFVuSTFjRzFPUlE9PSIsIm9yZ19pZCI6Im9yZ19HNzlFbXVuSjZON2d5MkhjIn0.bs9bIJaD7NBmZdUoDBdEzrl_jt9zMuLxpziwHucP5W94-EJOLPHKdQ09h70C85TR5OBEBvgP99Vktz2aYpvEYEpOxv2wWwoVvVIcUhLMfzdWGKURh7leOhIHM2pB1TDIyu7WY__ulCXskMrmQAXy_fCwOtb52mzDf_FdW6PljCHOLXSku4jNcNqc2g1tRrTNtmj1IT3YHveRv1kBJ5nwzucOZGNCocSe8Mjnx-5UgwOCKwzg-KocOCzvUsjXOw1-_p0lpazJAj0xkrJtCER8OVwiBLXNieX1sF4hbkbfjiHhQS6LJ5OdBhFlaEs3eefNVhYCptmvH3eo7h6QIQgBWQ
  - name: oidc
    user:
      exec:
        apiVersion: client.authentication.k8s.io/v1beta1
        args:
          - oidc-login
          - get-token
          - '--oidc-issuer-url=https://login.spot.rackspace.com/'
          - '--oidc-client-id=mwG3lUMV8KyeMqHe4fJ5Bb3nM1vBvRNa'
          - '--oidc-extra-scope=openid'
          - '--oidc-extra-scope=profile'
          - '--oidc-extra-scope=email'
          - '--oidc-auth-request-extra-params=organization=org_G79EmunJ6N7gy2Hc'
          - '--token-cache-dir=~/.kube/cache/oidc-login/org_G79EmunJ6N7gy2Hc'
        command: kubectl
        env: null
        interactiveMode: IfAvailable
        provideClusterInfo: false
