apiVersion: v1
clusters:
  - cluster:
      insecure-skip-tls-verify: true
      server: >-
        https://vcp-ef696d76-e041-4031-818b-b33e78af78c.cloud-171791500.spot.rackspace.com/
    name: burst1
contexts:
  - context:
      cluster: burst1
      namespace: default
      user: ngpc-user
    name: aws-burst1
  - context:
      cluster: burst1
      namespace: default
      user: oidc
    name: aws-burst1-oidc
current-context: aws-burst1
kind: Config
preferences: {}
users:
  - name: ngpc-user
    user:
      token: >-
        eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IkNYQ25nd1NFS0JWQl9DbWxvalo0eCJ9.eyJncm91cC6ImNsb3Vkc3BhY2UtYWRtaW4iLCJnaXZlbl9uYW1lIjoiRXRoYW4iLCJmYW1pbHlfbmFtZSI6IkNvb3BlciIsIm5pY2tuYW1lIjoiaG9vbjMzNzEwIiwibmFtZSI6IkV0aGFuIENvb3BlciIsInBpY3R1cmUiOiJodHRwczovL2xoMy5nb29nbGV1c2VyY29udGVudC5jb20vYS9BQ2c4b2NKNmVuZUJQYl9ud0ZrSno3V2dyaElfXzEyNkVsZklzWHdkaDNudkxuMmZybU1Ub1E9czk2LWMiLCJ1cGRhdGVkX2F0IjoiMjAyNC0wNi0xMVQwMzowODoxMS45OTNaIiwiZW1haWwiOiJob29uMzM3MTBAZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsImlzcyI6Imh0dHBzOi8vbG9naW4uc3BvdC5yYWNrc3BhY2UuY29tLyIsImF1ZCI6Im13RzNsVU1WOEt5ZU1xSGU0Zko1QmIzbk0xdkJ2Uk5hIiwiaWF0IjoxNzE4MjAxMjA5LCJleHAiOjE3MTg0NjA0MDksInN1YiI6Imdvb2dsZS1vYXV0aDJ8MTA3NTEzODg4NjU4OTA2MzkxNDYwIiwic2lkIjoiV0VuS21fbjJjVDVBLV84VUVWSWlWMEJxQlJhXluQVQiLCJub25jZSI6ImMzTjVkRU5EU25OdlRWOUNiVFpZU1M0M2JVMXpaMEl4Y0cxZldqSkhOMkpMZDJ0alExaEJZazE1VUE9PSIsIm9yZ19pZCI6Im9yZ19HNzlFbXVuSjZON2d5MkhjIn0.D8kdRUrDWaVnY6_SiKXJYkcJNRz-_M3T9RwFuMKujGcSl0ZrBthXyWyM84lnlcS-Y8L2RG6ob2GQ9trnJXNwzq6lEML6Jt5vZezFcLD_1wCRm-c01CEthL9pLQxSnoR7vjdcE7eYHBHOn6ptq3am_iG_kJYt7cJ4EwqIvTYB7TchY8Bx-wgruZ4cItAHtqT4sF28y36LDn5fOMDKmPdHraqnW-bAWZRyWxFYUmaRaAGQHSbQbSfcQK7QS8a1xjle7C_PioU85F-Buq1YeVaAI4iY1hHzfMkp9AHqaZByxETiSNoIt-YCmtIEaE4JntwXncG8Pt1wF2drR5xuQYA__w
  - name: oidc
    user:
      exec:
        apiVersion: client.authentication.k8s.io/v1beta1
        args:
          - oidc-login
          - get-token
          - '--oidc-issuer-url=https://login.spot.rackspace.com/'
          - '--oidc-client-id=mwG3lUMV8KyeMqHe4fJ5Bb3nM1vBvRNa'
          - '--oidc-extra-scope=openid'
          - '--oidc-extra-scope=profile'
          - '--oidc-extra-scope=email'
          - '--oidc-auth-request-extra-params=organization=org_G79EmunJ6N7gy2Hc'
          - '--token-cache-dir=~/.kube/cache/oidc-login/org_G79EmunJ6N7gy2Hc'
        command: kubectl
        env: null
        interactiveMode: IfAvailable
        provideClusterInfo: false

